### ISSUE TITLE
Uncaught TypeError: _this.log is not a function

### ISSUE THREAD

**Issue by miklb** [peterjohnhunt/wordpress-suite#10]
After restart after updating to 1.0

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [wordpress-suite](https://github.com/peterjohnhunt/wordpress-suite) package 1.0.0

### Stack Trace

Uncaught TypeError: _this.log is not a function

```
At /Users/miklb/.atom/packages/wordpress-suite/lib/main.coffee:13

TypeError: _this.log is not a function
    at /packages/wordpress-suite/lib/main.coffee:13:5
```

### Commands

```
     -0:36.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-css-comb 3.1.0 
atom-liquid-snippets 0.3.0 
atomic-chrome 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
autoprefixer 3.7.0 
busy-signal 1.4.1 
civic-syntax 0.2.4 
CMB-Snippets 0.1.3 
docblockr 0.10.3 
edit-in-new-tab 0.10.0 
editorconfig 2.2.2 
file-icons 2.1.6 
gist 0.4.0 
imdone-atom 2.2.6 
intentions 1.1.2 
language-generic-config 1.3.0 
language-liquid 0.5.1 
language-log 1.8.0 
language-nginx 0.8.0 
linter 2.1.4 
linter-alex 4.0.0 
linter-eslint 8.1.7 
linter-js-standard 3.9.1 
linter-js-yaml 1.2.7 
linter-just-say-no 0.7.3 
linter-phpcs 1.6.4 
linter-proselint 3.2.1 
linter-sass-lint 1.7.4 
linter-stylelint 3.10.0 
linter-ui-default 1.5.4 
merge-conflicts 1.4.5 
oceanic-next 1.0.0 
pigments 0.39.1 
pretty-json 1.6.3 
project-manager 3.3.4 
react 0.16.2 
remove-whitespace 0.2.1 
sort-lines 0.14.0 
split-diff 1.4.0 
ssh-config 0.10.1 
stylefmt 4.1.1 
tabs-to-spaces 1.0.3 
toggl 0.6.0 
windows-carriage-return-remover 0.1.3 
wordpress-autocomplete 1.1.4 
wordpress-suite 1.0.0 
wp-dev 0.3.5 
```

**Comment by peterjohnhunt** [comment]
Whoops! Lingering dev environment stuff. Should be fixed now!
